openapi: 3.0.3
info:
  title: Users API server
  description: Users restful API
  version: "1.0"
servers:
- url: http://localhost:8000
  description: user hosts the User Service.
- url: http://0.0.0.0:8000
  description: user hosts the User Service.
paths:
  /users:
    post:
      tags:
      - usersAPI
      summary: add usersAPI
      description: Add a new user.
      operationId: usersAPI#add
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddRequestBody'
            example:
              password: Cumque aspernatur.
              username: Et asperiores non consequatur occaecati.
      responses:
        "201":
          description: Created response.
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /users/{id}:
    get:
      tags:
      - usersAPI
      summary: get usersAPI
      description: Get user by id.
      operationId: usersAPI#get
      parameters:
      - name: id
        in: path
        description: user id
        required: true
        schema:
          type: string
          description: user id
          example: Vitae vero quo.
        example: Natus facere labore atque.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddRequestBody'
              example:
                password: Vero error aut eveniet excepturi.
                username: Dicta laborum quia porro est et.
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
components:
  schemas:
    AddRequestBody:
      type: object
      properties:
        password:
          type: string
          example: Fugit ipsum deserunt aliquid.
        username:
          type: string
          example: Et laudantium commodi sed.
      example:
        password: Quis perferendis eum laborum in.
        username: Et dolores dolores fugit labore aliquid.
      required:
      - username
      - password
    Error:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: true
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: false
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: false
      example:
        id: 3F1FKVRR
        message: Value of ID must be an integer
        name: bad_request
      required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
